version: "3"
services:
    nginx:
        image: nginx:latest
        container_name: webserver
        restart: unless-stopped
        ports:
            - 8080:443
        networks:
            - monitoring
        volumes:
            - ./configs/nginx-dev.conf:/etc/nginx/conf.d/default.conf
            - ./configs/ssl:/etc/nginx/ssl

    prometheus:
        image: prom/prometheus
        volumes:
            - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        networks:
            - monitoring
        extra_hosts:
            - "host.docker.internal:host-gateway"

    node-exporter:
        image: prom/node-exporter
        ports:
            - "9100:9100"
        networks:
            - monitoring
        extra_hosts:
            - "host.docker.internal:host-gateway"

    promtail:
        image: grafana/promtail
        volumes:
            - ./configs/promtail-config.yaml:/etc/promtail/config.yaml
        command: -config.expand-env=true
        networks:
            - monitoring
        extra_hosts:
            - "host.docker.internal:host-gateway"

    grafana:
        image: grafana/grafana
        ports:
            - "4000:3000"
        depends_on:
            - prometheus
            - promtail
        networks:
            - monitoring
        volumes:
            - ./configs/grafana.ini:/etc/grafana/grafana.ini # Mount custom grafana.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"

    loki:
        image: grafana/loki
        ports:
            - "3100:3100"
        volumes:
            - ./configs/loki-local-config.yaml:/etc/loki/local-config.yaml
        networks:
            - monitoring
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
    monitoring:
