global:
    scrape_interval: 5s

scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["server_prometheus_1:9090"]

    - job_name: "node_exporter"
      static_configs:
          - targets: ["server_node-exporter_1:9100"]

    - job_name: "elkhedewya"
      scrape_interval: 1s
      static_configs:
          - targets: ["host.docker.internal:9110"]

    - job_name: "loki"
      scrape_interval: 1s
      static_configs:
          - targets: ["server_loki_1:3100"]

    - job_name: "grafana"
      static_configs:
          - targets: ["server_grafana_1:3000"]
